add_test( [==[eig_sym and svd]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[eig_sym and svd]==]  )
set_tests_properties( [==[eig_sym and svd]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
add_test( [==[chol and lu]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[chol and lu]==]  )
set_tests_properties( [==[chol and lu]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
add_test( [==[solve and inverse]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[solve and inverse]==]  )
set_tests_properties( [==[solve and inverse]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
add_test( [==[Cube and Field indexing]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[Cube and Field indexing]==]  )
set_tests_properties( [==[Cube and Field indexing]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
add_test( [==[Mat basics and arithmetic]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[Mat basics and arithmetic]==]  )
set_tests_properties( [==[Mat basics and arithmetic]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
add_test( [==[Factory and transform helpers]==] /Users/kisung/Desktop/Dingo/build-noblas/tests/dingo-tests [==[Factory and transform helpers]==]  )
set_tests_properties( [==[Factory and transform helpers]==] PROPERTIES WORKING_DIRECTORY /Users/kisung/Desktop/Dingo/build-noblas/tests SKIP_RETURN_CODE 4)
set( dingo-tests_TESTS [==[eig_sym and svd]==] [==[chol and lu]==] [==[solve and inverse]==] [==[Cube and Field indexing]==] [==[Mat basics and arithmetic]==] [==[Factory and transform helpers]==])
